## 라이브러리 패키지 호출

In [3]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import export_graphviz
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.svm import LinearSVC
from sklearn.svm import SVC
from xgboost import XGBClassifier
from xgboost import XGBRegressor
from xgboost import plot_importance
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.model_selection import GridSearchCV
from catboost import CatBoostClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, recall_score, confusion_matrix, precision_score, f1_score, classification_report, mean_squared_error, r2_score
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OrdinalEncoder
from sklearn import preprocessing
from sklearn.cluster import KMeans
from imblearn.combine import SMOTEENN
from imblearn.over_sampling import * 
from imblearn.under_sampling import *
from lightgbm import LGBMClassifier

import os
import sys
sys.path.append(os.pardir)
import graphviz
import warnings
import pandas as pd
import numpy as np

In [ ]:
# RandomUnderSampler : 랜덤하게 샘플링(무작위)
# -> Tomek links : 두 범주 사이를 탐지하고 정리를 통해 부정확학 분류경계선 방지
# CondensedNearestNeighbour : 이상 범주 전체와 다수 정상에서 무작위로 하나의 관측치를 선택하여 서브 데이터를 구성
# -> I-NN알고리즘을 통해 원데이터를 분류 이상과 정상에서의 가까운 값을 바꾸어 준다. / 정상 분류된 다수 범주 관측치를 제거
# OneSidedSelection : Tomek links + CNN  합친거

In [ ]:
# Cost swnsitive learning
# Support vector data defcription(SVDD)

### 모든 행,열 전부 다 출력
- 주의할것 실행시키면 오래걸림

In [ ]:
# pd.set_option('display.max_columns',None)
# pd.set_option('display.max_rows',None)

### 데이터 호출
- kaggle 데이터 셋 heart_2020_cleaned.csv

In [4]:
df = pd.read_csv('C:/Users/gjaischool/VS/itIT/data/heart_2020_cleaned.csv')
df

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
0,No,16.60,Yes,No,No,3.0,30.0,No,Female,55-59,White,Yes,Yes,Very good,5.0,Yes,No,Yes
1,No,20.34,No,No,Yes,0.0,0.0,No,Female,80 or older,White,No,Yes,Very good,7.0,No,No,No
2,No,26.58,Yes,No,No,20.0,30.0,No,Male,65-69,White,Yes,Yes,Fair,8.0,Yes,No,No
3,No,24.21,No,No,No,0.0,0.0,No,Female,75-79,White,No,No,Good,6.0,No,No,Yes
4,No,23.71,No,No,No,28.0,0.0,Yes,Female,40-44,White,No,Yes,Very good,8.0,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319790,Yes,27.41,Yes,No,No,7.0,0.0,Yes,Male,60-64,Hispanic,Yes,No,Fair,6.0,Yes,No,No
319791,No,29.84,Yes,No,No,0.0,0.0,No,Male,35-39,Hispanic,No,Yes,Very good,5.0,Yes,No,No
319792,No,24.24,No,No,No,0.0,0.0,No,Female,45-49,Hispanic,No,Yes,Good,6.0,No,No,No
319793,No,32.81,No,No,No,0.0,0.0,No,Female,25-29,Hispanic,No,No,Good,12.0,No,No,No
319794,No,46.56,No,No,No,0.0,0.0,No,Female,80 or older,Hispanic,No,Yes,Good,8.0,No,No,No

### 데이터 설명
- HeartDisease 심장질환 :관상 동맥 심장 질환(CHD) 또는 심근 경색증(MI)이 있다고 보고한 적이 있는 응답자.
- BMI: 체질량  지수
- Smoking 흡연 : 일생동안 최소 100개피의 담배를 피웠는가?
- AlcoholDrinking 알코올음주 : 성인남자는 14잔 이상, 여성은 7잔 이상 이면 과음자
- Stroke 뇌졸증 : 뇌졸중이 있는가
- PhysicalHealth 신체 건강 : 지난 30일 동안 신체건강이 좋지 않을 날이 며칠인가(0일~30일)
- MentalHealth 정신 건강 : 지난 30일 동안 정신건강이 좋지 않을 날이 며칠인가(0일~30일)
- DiffWalking 디프워킹 : 걷거나 계단을 오를때 힘든적이 있는가?
- Sex 성별 : 남자(male), 여자(female)
- AgeCategory 나이카테고리 : 14단계 연령 범주
- (18 ~ 80 or older까지 각 14단계, 나이를 10대 단위로 4살차이로 구분)
- Race 인종: 백인, 라틴계 미국인, 흑인,기타 인종,아시아인, 인디언인/알레스카인
- Diabetic 당뇨병 : 당뇨병이 있습니까?
- PhysicalActivity 신체 활동 : 30일 동안 정규업무 이외의 신체활동 또는 운동을 했다고 하는 성인
- GenHealth	 젠 헬스 : 일반적인 건강 상태
- SleepTime 수면시간 : 24시간 중 평균 몇시간의 수면을 취하십니까?
- Asthma 천식 : 천식이 있습니까?
- KidneyDisease 신장병 : 신장결석, 방광 감염, 요심금을 제외하고 신장질환이 있는가?
- SkinCancer 피부암 : 피부암이 있는가?

### 전체 데이터 정보

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 319795 entries, 0 to 319794
Data columns (total 18 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   HeartDisease      319795 non-null  object
 1   BMI               319795 non-null  float64
 2   Smoking           319795 non-null  object
 3   AlcoholDrinking   319795 non-null  object
 4   Stroke            319795 non-null  object
 5   PhysicalHealth    319795 non-null  float64
 6   MentalHealth      319795 non-null  float64
 7   DiffWalking       319795 non-null  object
 8   Sex               319795 non-null  object
 9   AgeCategory       319795 non-null  object
 10  Race              319795 non-null  object
 11  Diabetic          319795 non-null  object
 12  PhysicalActivity  319795 non-null  object
 13  GenHealth         319795 non-null  object
 14  SleepTime         319795 non-null  float64
 15  Asthma            319795 non-null  object
 16  KidneyDisease     319795 non-null  object
 17  SkinCancer        319795 non-null  object
dtypes: float64(4), object(14)
memory usage: 43.9+ MB

### 전체 데이터 컴럼보기

In [4]:
df.columns

Index(['HeartDisease', 'BMI', 'Smoking', 'AlcoholDrinking', 'Stroke',
       'PhysicalHealth', 'MentalHealth', 'DiffWalking', 'Sex', 'AgeCategory',
       'Race', 'Diabetic', 'PhysicalActivity', 'GenHealth', 'SleepTime',
       'Asthma', 'KidneyDisease', 'SkinCancer'],
      dtype='object')

### 각 데이터 value_count보기

In [5]:
df['HeartDisease'].value_counts()

No     292422
Yes     27373
Name: HeartDisease, dtype: int64

In [6]:
df['BMI'].value_counts()

26.63    3762
27.46    2767
27.44    2723
24.41    2696
27.12    2525
         ...
59.85       1
50.59       1
92.53       1
62.95       1
46.56       1
Name: BMI, Length: 3604, dtype: int64

In [7]:
df['Smoking'].value_counts()

No     187887
Yes    131908
Name: Smoking, dtype: int64

In [ ]:
df['AlcoholDrinking'].value_counts()

In [ ]:
df['Stroke'].value_counts()

In [ ]:
df['PhysicalHealth'].value_counts()

In [ ]:
df['MentalHealth'].value_counts()

In [ ]:
df['DiffWalking'].value_counts()

In [ ]:
df['Sex'].value_counts()

In [ ]:
df['AgeCategory'].value_counts()

In [ ]:
df['Race'].value_counts()

In [ ]:
df['Diabetic'].value_counts()

### borderline diabtes : 경계성 당뇨 : 당뇨 전 단계
### during pregnancy : 임신 중

In [ ]:
df['PhysicalActivity'].value_counts()

In [ ]:
df['GenHealth'].value_counts()

In [ ]:
df['SleepTime'].value_counts()

In [ ]:
df['Asthma'].value_counts()

In [ ]:
df['KidneyDisease'].value_counts()

In [ ]:
df['SkinCancer'].value_counts()

### 범주형값을 수치값으로 변환(AgeCategory, Diabetic)
- OrfinalEncoder으로 라베링 실시
- AgeCategory, Diabetic값 OrdinalEncoder로 변환

In [5]:
one_dr_encoder = OrdinalEncoder()

In [6]:
age_df = df[['AgeCategory']]
age_df

        AgeCategory
0             55-59
1       80 or older
2             65-69
3             75-79
4             40-44
...             ...
319790        60-64
319791        35-39
319792        45-49
319793        25-29
319794  80 or older

[319795 rows x 1 columns]

In [7]:
df_age = one_dr_encoder.fit_transform(age_df)
o_e_df= pd.DataFrame(df_age, columns=['Age'])
o_e_df.value_counts()

Age
9.0     34151
8.0     33686
10.0    31065
7.0     29757
6.0     25382
12.0    24153
5.0     21791
11.0    21482
0.0     21064
4.0     21006
3.0     20550
2.0     18753
1.0     16955
dtype: int64

In [8]:
df_diab= df[['Diabetic']]
df_diab.value_counts()

Diabetic
No                         269653
Yes                         40802
No, borderline diabetes      6781
Yes (during pregnancy)       2559
dtype: int64

In [9]:
o_e_di = one_dr_encoder.fit_transform(df_diab)
di = pd.DataFrame(o_e_di, columns = ['Diabetic'])
di.value_counts()

Diabetic
0.0         269653
2.0          40802
1.0           6781
3.0           2559
dtype: int64

In [10]:
di = di.replace({'Diabetic': 1}, 0)
di = di.replace({'Diabetic': 2}, 1)
di = di.replace({'Diabetic': 3}, 1)
di

        Diabetic
0            1.0
1            0.0
2            1.0
3            0.0
4            0.0
...          ...
319790       1.0
319791       0.0
319792       0.0
319793       0.0
319794       0.0

[319795 rows x 1 columns]

### Diabetic 값 제거

In [11]:
X_df = df.drop(columns=['Diabetic'],axis=1)
X_df

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
0,No,16.60,Yes,No,No,3.0,30.0,No,Female,55-59,White,Yes,Very good,5.0,Yes,No,Yes
1,No,20.34,No,No,Yes,0.0,0.0,No,Female,80 or older,White,Yes,Very good,7.0,No,No,No
2,No,26.58,Yes,No,No,20.0,30.0,No,Male,65-69,White,Yes,Fair,8.0,Yes,No,No
3,No,24.21,No,No,No,0.0,0.0,No,Female,75-79,White,No,Good,6.0,No,No,Yes
4,No,23.71,No,No,No,28.0,0.0,Yes,Female,40-44,White,Yes,Very good,8.0,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319790,Yes,27.41,Yes,No,No,7.0,0.0,Yes,Male,60-64,Hispanic,No,Fair,6.0,Yes,No,No
319791,No,29.84,Yes,No,No,0.0,0.0,No,Male,35-39,Hispanic,Yes,Very good,5.0,Yes,No,No
319792,No,24.24,No,No,No,0.0,0.0,No,Female,45-49,Hispanic,Yes,Good,6.0,No,No,No
319793,No,32.81,No,No,No,0.0,0.0,No,Female,25-29,Hispanic,No,Good,12.0,No,No,No
319794,No,46.56,No,No,No,0.0,0.0,No,Female,80 or older,Hispanic,Yes,Good,8.0,No,No,No

### 변환했던 값 concat으로 합치기
- o_e_df : AgeCategory
- di : Diabetic

In [12]:
X_df = pd.concat([X_df, o_e_df, di], axis=1, join='inner') 
X_df

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer,Age,Diabetic
0,No,16.60,Yes,No,No,3.0,30.0,No,Female,55-59,White,Yes,Very good,5.0,Yes,No,Yes,7.0,1.0
1,No,20.34,No,No,Yes,0.0,0.0,No,Female,80 or older,White,Yes,Very good,7.0,No,No,No,12.0,0.0
2,No,26.58,Yes,No,No,20.0,30.0,No,Male,65-69,White,Yes,Fair,8.0,Yes,No,No,9.0,1.0
3,No,24.21,No,No,No,0.0,0.0,No,Female,75-79,White,No,Good,6.0,No,No,Yes,11.0,0.0
4,No,23.71,No,No,No,28.0,0.0,Yes,Female,40-44,White,Yes,Very good,8.0,No,No,No,4.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319790,Yes,27.41,Yes,No,No,7.0,0.0,Yes,Male,60-64,Hispanic,No,Fair,6.0,Yes,No,No,8.0,1.0
319791,No,29.84,Yes,No,No,0.0,0.0,No,Male,35-39,Hispanic,Yes,Very good,5.0,Yes,No,No,3.0,0.0
319792,No,24.24,No,No,No,0.0,0.0,No,Female,45-49,Hispanic,Yes,Good,6.0,No,No,No,5.0,0.0
319793,No,32.81,No,No,No,0.0,0.0,No,Female,25-29,Hispanic,No,Good,12.0,No,No,No,1.0,0.0
319794,No,46.56,No,No,No,0.0,0.0,No,Female,80 or older,Hispanic,Yes,Good,8.0,No,No,No,12.0,0.0

### 나이구간을 구분하여 컬럼 지정

In [13]:
bins = [-1,1,3,5,7,13]
group_name = [1,2,3,4,5]
categorise = pd.cut(X_df['Age'],bins,labels=group_name)
X_df['Age']=categorise
X_df

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer,Age,Diabetic
0,No,16.60,Yes,No,No,3.0,30.0,No,Female,55-59,White,Yes,Very good,5.0,Yes,No,Yes,4,1.0
1,No,20.34,No,No,Yes,0.0,0.0,No,Female,80 or older,White,Yes,Very good,7.0,No,No,No,5,0.0
2,No,26.58,Yes,No,No,20.0,30.0,No,Male,65-69,White,Yes,Fair,8.0,Yes,No,No,5,1.0
3,No,24.21,No,No,No,0.0,0.0,No,Female,75-79,White,No,Good,6.0,No,No,Yes,5,0.0
4,No,23.71,No,No,No,28.0,0.0,Yes,Female,40-44,White,Yes,Very good,8.0,No,No,No,3,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319790,Yes,27.41,Yes,No,No,7.0,0.0,Yes,Male,60-64,Hispanic,No,Fair,6.0,Yes,No,No,5,1.0
319791,No,29.84,Yes,No,No,0.0,0.0,No,Male,35-39,Hispanic,Yes,Very good,5.0,Yes,No,No,2,0.0
319792,No,24.24,No,No,No,0.0,0.0,No,Female,45-49,Hispanic,Yes,Good,6.0,No,No,No,3,0.0
319793,No,32.81,No,No,No,0.0,0.0,No,Female,25-29,Hispanic,No,Good,12.0,No,No,No,1,0.0
319794,No,46.56,No,No,No,0.0,0.0,No,Female,80 or older,Hispanic,Yes,Good,8.0,No,No,No,5,0.0

### Age타입 변경 : int64

In [14]:
X1_df = X_df.astype({'Age':'int64'})

In [15]:
X1_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 319795 entries, 0 to 319794
Data columns (total 19 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   HeartDisease      319795 non-null  object
 1   BMI               319795 non-null  float64
 2   Smoking           319795 non-null  object
 3   AlcoholDrinking   319795 non-null  object
 4   Stroke            319795 non-null  object
 5   PhysicalHealth    319795 non-null  float64
 6   MentalHealth      319795 non-null  float64
 7   DiffWalking       319795 non-null  object
 8   Sex               319795 non-null  object
 9   AgeCategory       319795 non-null  object
 10  Race              319795 non-null  object
 11  PhysicalActivity  319795 non-null  object
 12  GenHealth         319795 non-null  object
 13  SleepTime         319795 non-null  float64
 14  Asthma            319795 non-null  object
 15  KidneyDisease     319795 non-null  object
 16  SkinCancer        319795 non-null  object
 17  Age               319795 non-null  int64
 18  Diabetic          319795 non-null  float64
dtypes: float64(5), int64(1), object(13)
memory usage: 46.4+ MB

In [16]:
X1_df_1 = X1_df.drop(columns=['AgeCategory'],axis=1)
X1_df_1

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,Race,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer,Age,Diabetic
0,No,16.60,Yes,No,No,3.0,30.0,No,Female,White,Yes,Very good,5.0,Yes,No,Yes,4,1.0
1,No,20.34,No,No,Yes,0.0,0.0,No,Female,White,Yes,Very good,7.0,No,No,No,5,0.0
2,No,26.58,Yes,No,No,20.0,30.0,No,Male,White,Yes,Fair,8.0,Yes,No,No,5,1.0
3,No,24.21,No,No,No,0.0,0.0,No,Female,White,No,Good,6.0,No,No,Yes,5,0.0
4,No,23.71,No,No,No,28.0,0.0,Yes,Female,White,Yes,Very good,8.0,No,No,No,3,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319790,Yes,27.41,Yes,No,No,7.0,0.0,Yes,Male,Hispanic,No,Fair,6.0,Yes,No,No,5,1.0
319791,No,29.84,Yes,No,No,0.0,0.0,No,Male,Hispanic,Yes,Very good,5.0,Yes,No,No,2,0.0
319792,No,24.24,No,No,No,0.0,0.0,No,Female,Hispanic,Yes,Good,6.0,No,No,No,3,0.0
319793,No,32.81,No,No,No,0.0,0.0,No,Female,Hispanic,No,Good,12.0,No,No,No,1,0.0
319794,No,46.56,No,No,No,0.0,0.0,No,Female,Hispanic,Yes,Good,8.0,No,No,No,5,0.0

### 불필요한 데이터 drop ('AgeCategory','PhysicalHealth','MentalHealth','Race','GenHealth')

In [17]:
X1_df_1 = X1_df_1.drop(columns=['Race','GenHealth','SkinCancer','PhysicalHealth','MentalHealth'],axis=1)
X1_df_1

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,DiffWalking,Sex,PhysicalActivity,SleepTime,Asthma,KidneyDisease,Age,Diabetic
0,No,16.60,Yes,No,No,No,Female,Yes,5.0,Yes,No,4,1.0
1,No,20.34,No,No,Yes,No,Female,Yes,7.0,No,No,5,0.0
2,No,26.58,Yes,No,No,No,Male,Yes,8.0,Yes,No,5,1.0
3,No,24.21,No,No,No,No,Female,No,6.0,No,No,5,0.0
4,No,23.71,No,No,No,Yes,Female,Yes,8.0,No,No,3,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
319790,Yes,27.41,Yes,No,No,Yes,Male,No,6.0,Yes,No,5,1.0
319791,No,29.84,Yes,No,No,No,Male,Yes,5.0,Yes,No,2,0.0
319792,No,24.24,No,No,No,No,Female,Yes,6.0,No,No,3,0.0
319793,No,32.81,No,No,No,No,Female,No,12.0,No,No,1,0.0
319794,No,46.56,No,No,No,No,Female,Yes,8.0,No,No,5,0.0

In [18]:
X1_df_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 319795 entries, 0 to 319794
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   HeartDisease      319795 non-null  object
 1   BMI               319795 non-null  float64
 2   Smoking           319795 non-null  object
 3   AlcoholDrinking   319795 non-null  object
 4   Stroke            319795 non-null  object
 5   DiffWalking       319795 non-null  object
 6   Sex               319795 non-null  object
 7   PhysicalActivity  319795 non-null  object
 8   SleepTime         319795 non-null  float64
 9   Asthma            319795 non-null  object
 10  KidneyDisease     319795 non-null  object
 11  Age               319795 non-null  int64
 12  Diabetic          319795 non-null  float64
dtypes: float64(3), int64(1), object(9)
memory usage: 31.7+ MB

In [19]:
X1_df_1['Age'].value_counts()

5    144537
4     55139
3     42797
2     39303
1     38019
Name: Age, dtype: int64

### 인코딩 작업
- 축약 if문 사용

In [20]:
X1_df_1['HeartDisease'] = [1 if each == 'Yes' else 0 for each in X1_df_1['HeartDisease']]

In [21]:
X1_df_1['Smoking'] = [1 if each == 'Yes' else 0 for each in X1_df_1['Smoking']]

In [22]:
X1_df_1['AlcoholDrinking'] = [1 if each == 'Yes' else 0 for each in X1_df_1['AlcoholDrinking']]

In [23]:
X1_df_1['Stroke'] = [1 if each == 'Yes' else 0 for each in X1_df_1['Stroke']]

In [24]:
X1_df_1['Sex'] = [1 if each == 'Male' else 0 for each in X1_df_1['Sex']]

In [25]:
X1_df_1['PhysicalActivity'] = [1 if each == 'Yes' else 0 for each in X1_df_1['PhysicalActivity']]

In [26]:
X1_df_1['DiffWalking'] = [1 if each == 'Yes' else 0 for each in X1_df_1['DiffWalking']]

In [27]:
X1_df_1['Asthma'] = [1 if each == 'Yes' else 0 for each in X1_df_1['Asthma']]

In [28]:
X1_df_1['KidneyDisease'] = [1 if each == 'Yes' else 0 for each in X1_df_1['KidneyDisease']]

In [29]:
X1_df_1

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,DiffWalking,Sex,PhysicalActivity,SleepTime,Asthma,KidneyDisease,Age,Diabetic
0,0,16.60,1,0,0,0,0,1,5.0,1,0,4,1.0
1,0,20.34,0,0,1,0,0,1,7.0,0,0,5,0.0
2,0,26.58,1,0,0,0,1,1,8.0,1,0,5,1.0
3,0,24.21,0,0,0,0,0,0,6.0,0,0,5,0.0
4,0,23.71,0,0,0,1,0,1,8.0,0,0,3,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
319790,1,27.41,1,0,0,1,1,0,6.0,1,0,5,1.0
319791,0,29.84,1,0,0,0,1,1,5.0,1,0,2,0.0
319792,0,24.24,0,0,0,0,0,1,6.0,0,0,3,0.0
319793,0,32.81,0,0,0,0,0,0,12.0,0,0,1,0.0
319794,0,46.56,0,0,0,0,0,1,8.0,0,0,5,0.0

### 지금까지 데이터 상관계수 보기

In [30]:
# corrmat = X1_df_1.corr()
# top_corr_fea = corrmat.index[abs(corrmat['HeartDisease'])>=0.3]
# top_corr_fea

In [31]:
# plt.figure(figsize=(23,23))
# g = sns.heatmap(X1_df_1.corr(), annot=True, cmap='RdYlGn')

### Y타겟(HeartDisease) 설정 및 제거

In [32]:
y_target = X1_df_1['HeartDisease']
y_target.value_counts()

0    292422
1     27373
Name: HeartDisease, dtype: int64

In [33]:
X1_df_1 = X1_df_1.drop(columns=['HeartDisease'],axis=1)
X1_df_1

,BMI,Smoking,AlcoholDrinking,Stroke,DiffWalking,Sex,PhysicalActivity,SleepTime,Asthma,KidneyDisease,Age,Diabetic
0,16.60,1,0,0,0,0,1,5.0,1,0,4,1.0
1,20.34,0,0,1,0,0,1,7.0,0,0,5,0.0
2,26.58,1,0,0,0,1,1,8.0,1,0,5,1.0
3,24.21,0,0,0,0,0,0,6.0,0,0,5,0.0
4,23.71,0,0,0,1,0,1,8.0,0,0,3,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
319790,27.41,1,0,0,1,1,0,6.0,1,0,5,1.0
319791,29.84,1,0,0,0,1,1,5.0,1,0,2,0.0
319792,24.24,0,0,0,0,0,1,6.0,0,0,3,0.0
319793,32.81,0,0,0,0,0,0,12.0,0,0,1,0.0
319794,46.56,0,0,0,0,0,1,8.0,0,0,5,0.0

### 구간값을 실수값으로 구분하여 레이블 저장 및 타입 변경 : 원래 -object / 변경타입 - int
- 0 ~ 18.50 : 저체중 / groupnames = 1
- 18.50 ~ 24.99 : 정상 / groupnames = 2
- 25.00 ~ 29.99 : 과체중 / groupnames = 3
- 30.00 ~ 34.99 : 1단계 비만 / groupnames = 4
- 35.00 ~ 39.99 : 2단계 비만 / groupnames = 5
- 40 ~ : 고도비만 / groupnames = 6

In [34]:
bins  = [0,18.50,24.99,29.99,34.99,39.99,99]
group_names = [1,2,3,4,5,6]   # bin a < 구간 <= b
categorise = pd.cut(X1_df_1['BMI'],bins,labels=group_names)
X1_df_1["BMI"]= categorise
X1_df_1['BMI'].value_counts()   # 1: 저체중 2:정상 3:과체중 4: 1단계비만 5: 2단계 비만 6: 고도비만

3    114512
2     97327
4     61345
5     25112
6     16385
1      5114
Name: BMI, dtype: int64

In [35]:
X1_df_1 = X1_df_1.astype({'BMI':'int64'})

In [36]:
X1_df_1

,BMI,Smoking,AlcoholDrinking,Stroke,DiffWalking,Sex,PhysicalActivity,SleepTime,Asthma,KidneyDisease,Age,Diabetic
0,1,1,0,0,0,0,1,5.0,1,0,4,1.0
1,2,0,0,1,0,0,1,7.0,0,0,5,0.0
2,3,1,0,0,0,1,1,8.0,1,0,5,1.0
3,2,0,0,0,0,0,0,6.0,0,0,5,0.0
4,2,0,0,0,1,0,1,8.0,0,0,3,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
319790,3,1,0,0,1,1,0,6.0,1,0,5,1.0
319791,3,1,0,0,0,1,1,5.0,1,0,2,0.0
319792,2,0,0,0,0,0,1,6.0,0,0,3,0.0
319793,4,0,0,0,0,0,0,12.0,0,0,1,0.0
319794,6,0,0,0,0,0,1,8.0,0,0,5,0.0

### 최종 데이터 상관계수 확인 및 나머지 값 타입 변경
- 최종데이터 : train_df

In [37]:
train_df = X1_df_1
train_df

,BMI,Smoking,AlcoholDrinking,Stroke,DiffWalking,Sex,PhysicalActivity,SleepTime,Asthma,KidneyDisease,Age,Diabetic
0,1,1,0,0,0,0,1,5.0,1,0,4,1.0
1,2,0,0,1,0,0,1,7.0,0,0,5,0.0
2,3,1,0,0,0,1,1,8.0,1,0,5,1.0
3,2,0,0,0,0,0,0,6.0,0,0,5,0.0
4,2,0,0,0,1,0,1,8.0,0,0,3,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
319790,3,1,0,0,1,1,0,6.0,1,0,5,1.0
319791,3,1,0,0,0,1,1,5.0,1,0,2,0.0
319792,2,0,0,0,0,0,1,6.0,0,0,3,0.0
319793,4,0,0,0,0,0,0,12.0,0,0,1,0.0
319794,6,0,0,0,0,0,1,8.0,0,0,5,0.0

In [38]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 319795 entries, 0 to 319794
Data columns (total 12 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   BMI               319795 non-null  int64
 1   Smoking           319795 non-null  int64
 2   AlcoholDrinking   319795 non-null  int64
 3   Stroke            319795 non-null  int64
 4   DiffWalking       319795 non-null  int64
 5   Sex               319795 non-null  int64
 6   PhysicalActivity  319795 non-null  int64
 7   SleepTime         319795 non-null  float64
 8   Asthma            319795 non-null  int64
 9   KidneyDisease     319795 non-null  int64
 10  Age               319795 non-null  int64
 11  Diabetic          319795 non-null  float64
dtypes: float64(2), int64(10)
memory usage: 29.3 MB

In [39]:
train_df = train_df.astype({'SleepTime':'int64'})
train_df = train_df.astype({'Diabetic':'int64'})

In [40]:
train_df

,BMI,Smoking,AlcoholDrinking,Stroke,DiffWalking,Sex,PhysicalActivity,SleepTime,Asthma,KidneyDisease,Age,Diabetic
0,1,1,0,0,0,0,1,5,1,0,4,1
1,2,0,0,1,0,0,1,7,0,0,5,0
2,3,1,0,0,0,1,1,8,1,0,5,1
3,2,0,0,0,0,0,0,6,0,0,5,0
4,2,0,0,0,1,0,1,8,0,0,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...
319790,3,1,0,0,1,1,0,6,1,0,5,1
319791,3,1,0,0,0,1,1,5,1,0,2,0
319792,2,0,0,0,0,0,1,6,0,0,3,0
319793,4,0,0,0,0,0,0,12,0,0,1,0
319794,6,0,0,0,0,0,1,8,0,0,5,0

In [41]:
# plt.figure(figsize=(23,23))
# g = sns.heatmap(train_df.corr(), annot=True, cmap='RdYlGn')

In [42]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 319795 entries, 0 to 319794
Data columns (total 12 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   BMI               319795 non-null  int64
 1   Smoking           319795 non-null  int64
 2   AlcoholDrinking   319795 non-null  int64
 3   Stroke            319795 non-null  int64
 4   DiffWalking       319795 non-null  int64
 5   Sex               319795 non-null  int64
 6   PhysicalActivity  319795 non-null  int64
 7   SleepTime         319795 non-null  int64
 8   Asthma            319795 non-null  int64
 9   KidneyDisease     319795 non-null  int64
 10  Age               319795 non-null  int64
 11  Diabetic          319795 non-null  int64
dtypes: int64(12)
memory usage: 29.3 MB

### 학습 및 정확도 확인, 변수중요도 확인

In [43]:
X = train_df

In [44]:
y = y_target

In [42]:
# X_train_valid, X_test, y_train_valid, y_test = train_test_split(X, y, test_size=0.05, stratify=y)
# X_train, X_train_valid, y_train, y_train_valid = train_test_split(X_train_valid, y_train_valid, test_size=0.05, stratify=y_train_valid)

In [43]:
# xgbr_all = XGBRegressor(n_estimators=100, learning_rate=0.1, max_depth=3, objective='reg:squarederror', radom_state=2021)
# xgbr_all.fit(X_train, y_train)
# pred = xgbr_all.predict(X_train_valid)

# rmse = np.sqrt(mean_squared_error(y_train_valid, pred))

# fig, ax = plt.subplots(figsize=(10,10))
# plot_importance(xgbr_all, ax=ax)

### SMOTEENN(복합샘플링)

In [46]:
smoenn = SMOTEENN(random_state=42)
X, y = smoenn.fit_resample(X,y)

In [45]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, stratify = y)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((255836, 12), (63959, 12), (255836,), (63959,))

### RandomForestRegressor

In [48]:
rf_model = RandomForestClassifier()
rf_model.fit(X_train, y_train)

y_pred = rf_model.predict(X_test)
# 오차행렬
print(confusion_matrix(y_test, y_pred))
# 정확도
print(accuracy_score(y_test, y_pred)*100)
# 정밀도
print(precision_score(y_test, y_pred)*100)
# 재현율
print(recall_score(y_test, y_pred)*100)
print(f1_score(y_test, y_pred)*100)
print(r2_score(y_test, y_pred)*100)

[[57679   805]
 [ 4974   501]]
90.96452414828249
38.36140888208269
9.150684931506849
14.776581625129037
-15.433846481526082

### LogisticRegression

In [46]:
lr_model = LogisticRegression()

parameters = {'C' :  [0.05,0.01,0.5,0.1,1,3,5,7,9],
              'max_iter':[100,200,500,1000],
              'penalty':['l2', 'l1']
              }

grid_lr_model = GridSearchCV(lr_model, param_grid=parameters, cv=3, refit=True)

grid_lr_model.fit(X_train, y_train)
pred_lr = grid_lr_model.predict(X_test)
scores_df = pd.DataFrame(grid_lr_model.cv_results_)
print('GridSearchCV 최적 파라미터:', grid_lr_model.best_params_)
print('GridSearchCV 최고 정확도: {0:.4f}'.format(grid_lr_model.best_score_))
print(confusion_matrix(y_test, pred_lr))
# 정확도
print(accuracy_score(y_test, pred_lr)*100)
# 정밀도
print(precision_score(y_test, pred_lr)*100)
# 재현율
print(recall_score(y_test, pred_lr)*100)
print(f1_score(y_test, pred_lr)*100)
print(r2_score(y_test, pred_lr)*100)

C:\Users\gjaischool\AppData\Roaming\Python\Python39\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\gjaischool\AppData\Roaming\Python\Python39\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\gjaischool\AppData\Roaming\Python\Python39\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\gjaischool\AppData\Roaming\Python\Python39\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\gjaischool\AppData\Roaming\Python\Python39\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\gjaischool\AppData\Roaming\Python\Python39\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\gjaischool\AppData\Roaming\Python\Python39\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\gjaischool\AppData\Roaming\Python\Python39\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\gjaischool\AppData\Roaming\Python\Python39\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\gjaischool\AppData\Roaming\Python\Python39\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\gjaischool\AppData\Roaming\Python\Python39\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\gjaischool\AppData\Roaming\Python\Python39\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\gjaischool\AppData\Roaming\Python\Python39\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\gjaischool\AppData\Roaming\Python\Python39\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\gjaischool\AppData\Roaming\Python\Python39\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\gjaischool\AppData\Roaming\Python\Python39\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\gjaischool\AppData\Roaming\Python\Python39\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\gjaischool\AppData\Roaming\Python\Python39\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\gjaischool\AppData\Roaming\Python\Python39\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\gjaischool\AppData\Roaming\Python\Python39\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\gjaischool\AppData\Roaming\Python\Python39\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\gjaischool\AppData\Roaming\Python\Python39\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\gjaischool\AppData\Roaming\Python\Python39\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\gjaischool\AppData\Roaming\Python\Python39\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\gjaischool\AppData\Roaming\Python\Python39\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\gjaischool\AppData\Roaming\Python\Python39\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\gjaischool\AppData\Roaming\Python\Python39\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\gjaischool\AppData\Roaming\Python\Python39\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\gjaischool\AppData\Roaming\Python\Python39\site-packages\sklearn\model_selection\_validation.py:378: FitFailedWarning:
108 fits failed out of a total of 216.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
108 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\gjaischool\AppData\Roaming\Python\Python39\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\gjaischool\AppData\Roaming\Python\Python39\site-packages\sklearn\linear_model\_logistic.py", line 1091, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "C:\Users\gjaischool\AppData\Roaming\Python\Python39\site-packages\sklearn\linear_model\_logistic.py", line 61, in _check_solver
    raise ValueError(
ValueError: Solver lbfgs supports only 'l2' or 'none' penalties, got l1 penalty.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\gjaischool\AppData\Roaming\Python\Python39\site-packages\sklearn\model_selection\_search.py:953: UserWarning: One or more of the test scores are non-finite: [0.81659288        nan 0.81659574        nan 0.81659574        nan
 0.81659574        nan 0.81651574        nan 0.81655288        nan
 0.81655288        nan 0.81655288        nan 0.81676432        nan
 0.81655574        nan 0.81655574        nan 0.81655574        nan
 0.81660431        nan 0.8165786         nan 0.8165786         nan
 0.8165786         nan 0.81650717        nan 0.81662717        nan
 0.81662717        nan 0.81662717        nan 0.81673575        nan
 0.81656431        nan 0.81656431        nan 0.81656431        nan
 0.81656717        nan 0.81657574        nan 0.81657574        nan
 0.81657574        nan 0.81666717        nan 0.8165586         nan
 0.81655574        nan 0.81655574        nan 0.81646145        nan
 0.81658431        nan 0.81658431        nan 0.81658431        nan]
  warnings.warn(

GridSearchCV 최적 파라미터: {'C': 0.5, 'max_iter': 100, 'penalty': 'l2'}
GridSearchCV 최고 정확도: 0.8168
[[40207 18277]
 [ 1138  4337]]
69.64461608217765
19.178385071194835
79.21461187214612
30.880415821139945
-287.808985886629

C:\Users\gjaischool\AppData\Roaming\Python\Python39\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

### DecisiontreeClassifier

In [47]:

dt_model = DecisionTreeClassifier(max_depth=20, min_samples_split=2)
# parameters = {'max_depth' :  [5,10,15,20],
#               'min_samples_split':[2,4,6,8]
#               }
# grid_dt_model = GridSearchCV(dt_model, param_grid=parameters, cv=3, refit=True)
dt_model.fit(X_train, y_train)

pred = dt_model.predict(X_test)
# scores_df = pd.DataFrame(dt_model.cv_results_)
# print('GridSearchCV 최적 파라미터:', dt_model.best_params_)
# print('GridSearchCV 최고 정확도: {0:.4f}'.format(grid_dt_model.best_score_))
print(confusion_matrix(y_test, pred))
# 정확도
print(accuracy_score(y_test, pred)*100)
# 정밀도
print(precision_score(y_test, pred)*100)
# 재현율
print(recall_score(y_test, pred)*100)
print(f1_score(y_test, pred)*100)
print(r2_score(y_test, pred)*100)
# dt_model.fit(X_train, y_train)
# pred_dt = dt_model.predict(X_test)
# accuracy_score(pred_dt, y_test)

[[45550 12934]
 [ 2418  3057]]
75.99712315702247
19.117003314364332
55.83561643835616
28.482251001583904
-206.65174099055

### KNN

In [48]:
knn_model = KNeighborsClassifier(n_neighbors=12, metric='euclidean', weights='distance')
knn_model.fit(X_train, y_train)
pred_knn = knn_model.predict(X_test)
print(confusion_matrix(y_test, pred_knn))
# 정확도
print(accuracy_score(y_test, pred_knn)*100)
# 정밀도
print(precision_score(y_test, pred_knn)*100)
# 재현율
print(recall_score(y_test, pred_knn)*100)
print(f1_score(y_test, pred_knn)*100)
print(r2_score(y_test, pred_knn)*100)

[[43397 15087]
 [ 2020  3455]]
73.25317781703905
18.633372883184123
63.10502283105023
28.771287005038097
-241.7073562483936

### GridSearchCV
- LogisticRegression, 교차검증하여 파라미터 값 설정
- RandomForestClassifier, 교차검증하여 파라미터 값 설정

In [ ]:
lr_model_1 = LogisticRegression()

lr_grid = {'solver':['liblinear', 'lbfgs'],
    'penalty':['l1', 'l2'],
    'C':[0.01, 0.1, 1, 5, 10 ]
}
lr_res = GridSearchCV(estimator = lr_model_1,
                     param_grid=lr_grid,
                     n_jobs= -1, cv=5)

lr_res.fit(X_train, y_train)
lr_res.score(X_train, y_train), lr_res.score(X_test, y_test), lr_res.best_params_

In [ ]:
lr_model = LogisticRegression(C=0.01, penalty='l1', solver='liblinear')
lr_model.fit(X_train, y_train)
pred = lr_model.predict(X_test)
# 오차행렬
print(confusion_matrix(y_test, pred))
# 정확도
print(accuracy_score(y_test, pred)*100)
# 정밀도
print(precision_score(y_test, pred)*100)
# 재현율
print(recall_score(y_test, pred)*100)
print(f1_score(y_test, pred)*100)
print(r2_score(y_test, pred)*100)

In [ ]:
dt_model = DecisionTreeClassifier(max_depth=5, min_samples_split=2)
dt_model.fit(X_train, y_train)
pred = lr_model.predict(X_test)
# 오차행렬
print(confusion_matrix(y_test, pred))
# 정확도
print(accuracy_score(y_test, pred)*100)
# 정밀도
print(precision_score(y_test, pred)*100)
# 재현율
print(recall_score(y_test, pred)*100)
print(f1_score(y_test, pred)*100)

### XGBclassifier 적용, 파라미터 튜닝

In [53]:
def get_clf_eval(y_test, pred=None, pred_proba=None):
    confusion = confusion_matrix(y_test, pred)
    accuracy = accuracy_score(y_test, pred)
    precision = precision_score(y_test, pred)
    recall = recall_score(y_test, pred)
    f1 = f1_score(y_test, pred)
#     roc_auc = roc_auc(y_test, pred_proba)
    print('오차행렬')
    print(confusion)
    print('정확도:{0:.4f},정밀도:{1:.4f},재현율:{2:.4f},F1{3:.4f}'.format(accuracy, precision, recall, f1))

In [54]:
def get_model_train_eval(model, ftr_train = None, ftr_test=None, tgt_train=None, tgt_test=None):
    model.fit(ftr_train, tgt_train)
    pred = model.predict(ftr_test)
    pred_proba = model.predict_proba(ftr_test)[:, 1]
    get_clf_eval(tgt_test, pred, pred_proba)

In [55]:
xgb_model = XGBClassifier(base_score = 0.5,
                          n_estimators = 300,
                          learning_rate = 0.1,
                          max_depth = 10,
                          scale_pos_weight= 3,
                          reg_lambda=400,
                          n_jobs=-1,
                          subsample=1,
                          colsample_bytree=1)
get_model_train_eval(xgb_model, ftr_train=X_train, ftr_test=X_test, tgt_train=y_train, tgt_test=y_test)

오차행렬
[[46404  1163]
 [  137  5713]]
정확도:0.9757,정밀도:0.8309,재현율:0.9766,F10.8978

In [56]:
xgb_model.score(X_train, y_train), xgb_model.score(X_test, y_test)

(0.9774463185877155, 0.9756631783889024)

In [ ]:
def get_clf_eval(y_test, pred=None, pred_proba=None):
    confusion = confusion_matrix(y_test, pred)
    accuracy = accuracy_score(y_test, pred)
    precision = precision_score(y_test, pred)
    recall = recall_score(y_test, pred)
    f1 = f1_score(y_test, pred)
#     roc_auc = roc_auc(y_test, pred_proba)
    print('오차행렬')
    print(confusion)
    print('정확도:{0:.4f},정밀도:{1:.4f},재현율:{2:.4f},F1{3:.4f}'.format(accuracy, precision, recall, f1))

In [ ]:
xgb_model = XGBRegressor()
xgb_model.fit(X_train, y_train)
pred = xgb_model.predict(X_test)
get_clf_eval(xgb_model, ftr_train=X_train, ftr_test=X_test, tgt_train=y_train, tgt_test=y_test)

In [ ]:
print(mean_squared_error(y_test, pred))

In [ ]:
xgb_model = XGBClassifier()

xgb_model_grid = {
    'n_estimators' : [100, 200, 400, 600],
    'learning_rate' : [0.01, 0.05, 0.1, 1],
    'max_depth' : [4, 6, 8, 10],
    'min_child_weight' :[2,4,6,8],
    'scale_pos_weight' :[0.01, 0.05, 0.1, 1],
    'reg_lambda' :[4,6,7,10],
    'subsample' : [0.5,0.7, 0.8,1],
    'colsample_bytree' : [0.5,0.7, 0.8,1],  
}
lr_res = GridSearchCV(estimator = xgb_model,
                     param_grid=xgb_model_grid,
                     n_jobs= -1, cv=5)

lr_res.fit(X_train, y_train)
lr_res.score(X_train, y_train), lr_res.score(X_test, y_test), lr_res.best_params_